altlinux/gpupdate

gpoa/frontend/systemd_applier.py
=> Revert "Workaround for key names in PReg value names"

gpoa/frontend/firefox_applier.py
Reported by ekorneechev at basealt.ru at 2020-01-28
=> Fix for samba_preg access in firefox_applier

LICENSE.md
Fix for https://github.com/altlinux/gpupdate/issues/15 .
=> License file

.gitmodules
Done because of request from Alexander Bokovoy (ab at samba.org).
=> GitHub wiki added as submodule

gpoa/gpupdate
Reported by Konstantin Belash.
=> Fix for 'None' username dropping to runner_factory

gpoa/frontend/appliers/control.py, gpoa/frontend/control_applier.py
Ветка создана заново, так как в предыдущей реализации была допущена ошибка. Плюс учтены замечания от sin@
=> Control applier handle both number and string values

dist/gpupdate-setup, gpoa/gpt/gpt.py, gpoa/util/samba.py, gpoa/util/windows.py, gpupdate.spec
Get machine local Registry policy in Samba backup format and add support domain_controller local policy profile.
=> Samba format: local.xml -> Machine/Registry.pol.xml

dist/gpupdate-setup
Command active-policy revert only name now and "unknown" if policy is not setted.
=> gpupdate-setup: add default-policy and update active-policy commands

gpoa/frontend/cifs_applier.py, gpoa/frontend/frontend_manager.py, gpoa/gpt/drives.py, gpoa/gpt/gpt.py, gpoa/storage/record_types.py, gpoa/storage/sqlite_registry.py, gpoa/templates/autofs_auto.j2, gpoa/templates/autofs_identity.j2, gpoa/templates/autofs_mountpoints.j2, gpoa/templates/gpupdate_mount.j2, gpoa/test/gpt/test_drives.py, gpupdate.spec
This PR introduces support for parsing `Drive.xml` files and creation of `/etc/auto.master` entries for corresponding Samba shares.
=> Autofs/CIFS applier for mounting Samba shares

gpoa/frontend/frontend_manager.py, gpoa/gpt/drives.py, gpoa/gpt/envvars.py, gpoa/gpt/files.py, gpoa/gpt/folders.py, gpoa/gpt/gpt.py, gpoa/gpt/inifiles.py, gpoa/gpt/polfile.py, gpoa/gpt/printers.py, gpoa/gpt/services.py, gpoa/gpt/shortcuts.py, gpoa/gpt/tasks.py, gpoa/storage/record_types.py, gpoa/storage/sqlite_registry.py, gpoa/util/preg.py
During applier implementation I accidentally reworked large parts of GPT parser and SQLite3 backend because of need for duplicate code and hardcode elimination. After this PR is merged there will still be room for improvement but here done the most tough work of logic rethink.
=> Backend refactoring

gpoa/frontend/appliers/folder.py, gpoa/frontend/folder_applier.py, gpoa/frontend/frontend_manager.py, gpoa/gpt/folders.py
The applier is implemented using new backend architecture.
=> Applier for Folders.xml

.gitignore, gpoa/frontend/applier_frontend.py, gpoa/frontend/chromium_applier.py, gpoa/frontend/cifs_applier.py, gpoa/frontend/control_applier.py, gpoa/frontend/cups_applier.py, gpoa/frontend/firefox_applier.py, gpoa/frontend/folder_applier.py, gpoa/frontend/frontend_manager.py, gpoa/frontend/gsettings_applier.py, gpoa/frontend/package_applier.py, gpoa/frontend/polkit_applier.py, gpoa/frontend/shortcut_applier.py, gpoa/frontend/systemd_applier.py
This PR enables the functionality to turn various `gpoa` modules on and off via Group Policies.
=> Experimental frontend modules' switch

gpoa/frontend/frontend_manager.py, gpoa/frontend/ntp_applier.py
This PR adds support for NTP configuration propagated via RSAT (Windows) settings.
=> NTP applier

gpoa/backend/__init__.py, gpoa/backend/samba_backend.py, gpoa/frontend/frontend_manager.py, gpoa/gpoa, gpoa/gpt/gpt.py, gpoa/gpupdate, gpoa/messages/__init__.py, gpoa/plugin/adp.py, gpoa/plugin/plugin_manager.py, gpoa/storage/sqlite_cache.py, gpoa/storage/sqlite_registry.py, gpoa/util/arguments.py, gpoa/util/dbus.py, gpoa/util/exceptions.py, gpoa/util/kerberos.py, gpoa/util/logging.py, gpoa/util/preg.py, gpoa/util/sid.py, gpoa/util/users.py, gpoa/util/windows.py, gpoa/util/xdg.py
This PR is the second in a series of improvements for log messages. Here we slowly migrating to translatable and parseable log messages which may be forwarded to log collectors for further analysis.
The messages after this PR is merged will look like:
```
[nir@comp gpoa]$ ./gpupdate
2020-07-23 18:23:02:[I00003]: Group Policy target set for update:{"target": "All"}
2020-07-23 18:23:02:[W00002]: Current permissions does not allow to perform gpupdate fordesignted user. Will update current user settings:{"username": null}
2020-07-23 18:23:02:[W00003]: oddjobd is inaccessible:{}
2020-07-23 18:23:02:[E00001]: Insufficient permissions to run gpupdate:{}
2020-07-23 18:23:02:[E00002]: gpupdate will not be started:{}
```
```
[nir@comp gpoa]$ ./gpoa --loglevel 0
2020-07-23 18:07:50:[D00001]: The …
```
=> Logging codes

gpoa/util/windows.py
Fix after https://github.com/altlinux/gpupdate/issues/98
=> Fixed set_dc()

gpoa/frontend/appliers/folder.py, gpoa/frontend/folder_applier.py, gpoa/gpt/folders.py, gpoa/storage/record_types.py, gpoa/storage/sqlite_registry.py
Another loss of storage compatibility because of mapping changes due to typo.
=> Folders regression fix

gpoa/frontend/appliers/gsettings.py, gpoa/frontend/gsettings_applier.py
GSettings applier: final and enable by default system part applied to machine.
=> GSettings applier for machine

gpoa/frontend/firefox_applier.py
Add boolean configs and fix it's support.
Fix boolean config for firefox applier and add support additional policies from:
https://github.com/mozilla/policy-templates/blob/master/README.md
=> Add support additional firefox appliers

gpoa/frontend/gsettings_applier.py
Added mapping for keys sleep-computer-ac and sleep-display-ac
=> Added keys sleep-computer-ac and sleep-display-ac

gpoa/frontend/appliers/gsettings.py, gpoa/frontend/frontend_manager.py, gpoa/messages/__init__.py, gpoa/util/dbus.py, gpoa/util/system.py, gpoa/util/users.py
Fix Dbus session killing with GSettings in user context applying.
=> Dbus session kill

gpoa/frontend/shortcut_applier.py, gpoa/gpt/shortcuts.py, gpoa/storage/sqlite_registry.py
Add support actions (create, update, delete, replace) for Shortcuts
=> Shortcuts actions

gpoa/frontend/appliers/folder.py, gpoa/frontend/folder_applier.py, gpoa/frontend/gsettings_applier.py, gpoa/gpt/folders.py, gpoa/templates/autofs_auto.j2, gpoa/util/windows.py
=> Gsettings experimental

gpoa/frontend/appliers/folder.py, gpoa/frontend/folder_applier.py, gpoa/gpt/folders.py, gpoa/util/windows.py
=> Folder delete action

gpoa/frontend/appliers/folder.py, gpoa/frontend/folder_applier.py, gpoa/gpt/folders.py, gpoa/templates/autofs_auto.j2, gpoa/util/windows.py
The --browse option creates empty folders for each mount-point in the file in order to prevent timeouts.
=> Autofs template

gpoa/frontend/cifs_applier.py, gpoa/frontend/frontend_manager.py, gpoa/gpt/drives.py, gpoa/locale/ru_RU/LC_MESSAGES/gpoa.po, gpoa/messages/__init__.py, gpoa/storage/record_types.py, gpoa/storage/sqlite_registry.py, gpoa/templates/autofs_auto_hide.j2, gpoa/templates/autofs_mountpoints.j2, gpoa/templates/autofs_mountpoints_hide.j2
Added drive mapping support for computer
=> Fix mapped drive

gpoa/frontend/appliers/ini_file.py, gpupdate.spec
=> Save comments in ini files

gpoa/frontend/appliers/ini_file.py, gpoa/util/gpoa_ini_parsing.py
and incorporating its usage in the editing of INI files in ini_applier
=> Enhancing the functionality of ConfigObj to preserve comments

gpoa/frontend/appliers/systemd.py, gpoa/frontend/cups_applier.py, gpoa/locale/ru_RU/LC_MESSAGES/gpoa.po, gpoa/messages/__init__.py
Added state for stopping the service.
=> Added state for stopping the service.
