altlinux/gpupdate

gpoa/frontend/systemd_applier.py
According to commit `601f432043be9c63b3675753c799aa4466753c66` in
`admx-basealt` there may be no dot symbols in PReg value names. This
commit adds workaround to transform '_' into '.' in systemd units'
names.
Please note that in the future systemd applier module might be
transformed to work with `Services.xml` file instead `Registry.pol` so
this clunky behavior won't be needed.
=> Workaround for key names in PReg value names

gpoa/plugin/plugin_manager.py
Log about `ADP` initialization only once.
=> Disable ADP plugin initialization logging

gpoa/gpt/gpt.py
There is no `machine_sid` variable and I was unable to find when it was eliminated. Anyway, the fix is pretty simple. The bug related is: https://github.com/altlinux/gpupdate/issues/31 .
=> gpt.gpt: Polfile merging quickfix

.gitignore, doc/gpupdate.1, gpoa/gpupdate, gpoa/util/arguments.py, gpoa/util/dbus.py
When we try to start `oddjobd` via `D-Bus` using gpupdate we may
get the following traceback:
```
Traceback (most recent call last):
File "/usr/bin/gpupdate", line 144, in <module>
main()
File "/usr/bin/gpupdate", line 139, in main
gpo_appliers[1].run()
File "/usr/lib/python3/site-packages/gpoa/util/dbus.py", line 48, in run
result = self.interface.gpupdate()
File "/usr/lib64/python3/site-packages/dbus/proxies.py", line 72, in __call__
return self._proxy_method(*args, **keywords)
File "/usr/lib64/python3/site-packages/dbus/proxies.py", line 147, in __call__
**keywords)
File "/usr/lib64/python3/site-packages/dbus/connection.py", line 653, in call_blocking
message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: …
```
=> D-Bus exception catch

gpoa/frontend/appliers/systemd.py
This commit fixes error on `gpupdate.service` unit start:
```
Unable to start systemd unit gpupdate.service
```
This error was caused by limited functionality on handling unit
states, especially for restartable units.
=> Fix service state handling

gpoa/test/util/test_rpm.py, gpoa/util/rpm.py
This PR introduces additional checks if packages are installed. This pre-check before starting APT-RPM is needed to reduce APT memory consumption while scanning RPM database.
=> RPM helper improved

gpoa/templates/autofs_mountpoints.j2
`$AUTOFS_UID` is ALT-specific variable which proved to be unstable across distributions.
=> Use USER variable instead of unstable AUTOFS_UID

gpoa/gpoa
Fix for regression introduced by incorrectly set `KRB5CCNAME`.
=> gpoa: Fixed KRB5CCNAME usage

gpoa/gpupdate, gpoa/messages/__init__.py
`gpupdate`'s messaging/logging mechanism is shitty. This PR introduces new mechanism - all messages referenced by their codes, the English text is hardcoded into application by default and other texts must be accessible via `gettext`. The drawback of technology is that messages are not
format strings, so logging logic need to be reworked.
On the other hand there is still structured logging wrapper which may be able to provide the necessary data formatting.
The strong part of technology is that users will be able to reference messages by codes.
=> Error codes

gpoa/storage/sqlite_registry.py
This PR fixes the following critical bug:
```
Backend execution error: Could not evaluate current criteria in Python: "Can't evaluate criteria against alternate class <class 'storage.record_types.samba_hkcu_preg'>". Specify 'fetch' or False for the synchronize_session parameter.
```
=> sqlite_registry: Fixed samba_hkcu_preg mapping in query

gpoa/util/preg.py
This commit fixes the following error:
```
2020-06-30 00:18:25:add_hkcu_entry: S-1-5-21-1609667327-4120075585-2415302043-1109 Software\BaseALT\Policies\GPUpdate 0 4
Traceback (most recent call last):
File "/usr/sbin/gpoa", line 145, in <module>
main()
File "/usr/sbin/gpoa", line 140, in main
controller.run()
File "/usr/sbin/gpoa", line 97, in run
self.start_backend()
File "/usr/sbin/gpoa", line 115, in start_backend
back.retrieve_and_store()
File "/usr/lib/python3/site-packages/gpoa/backend/samba_backend.py", line 71, in retrieve_and_store
gptobj.merge()
File "/usr/lib/python3/site-packages/gpoa/gpt/gpt.py", line 219, in merge
preference_merger(self.storage, self.sid, preference_objects, self.name)
File "/usr/lib/python3/site-packages/gpoa/gpt/polfile.py", line 31, in merge_polfile …
```
=> Fix TALLOC ownership problem in PReg parser

gpupdate.spec
There are situations when we might lose storage compatibility between
versions due to SQLite3 table structure changes. This commit introduces
trigger which removes old storage in case of specific version change.
The storage will be regenerated on next GPOA run.
=> Postinst trigger introduced

gpoa/frontend/shortcut_applier.py
Run update-desktop-database utility only in case there are
shortcuts for processing present in storage.
=> Shortcuts applier improvement

gpoa/backend/__init__.py, gpoa/locale/ru_RU/LC_MESSAGES/gpoa.po, gpoa/messages/__init__.py, gpoa/util/config.py
It is now possible to write in `/etc/gpupdate/gpupdate.ini`:
```
[samba]
dc = your.buggy.dc
```
To avoid auto-selection of Domain Controller for policy replication.
=> Added functionality to tune Samba backend via INI file

gpoa/util/dbus.py
`python-dbus` `Interface` and `Object` primitives are unable to provide
methods allowing to set synchronous blocking call timeout. The problem
is that default D-Bus timeout is only 25 seconds while application of
Group Policy Objects takes 2-5 minutes. It was decided to set blocking
call timeout to 10 minutes using `call_blocking` method of `Connection`
primitive to solve the problem.
This change also requires correspondings changes in `oddjobd` and `oddjob-gpupdate` interfaces.
=> Increase D-Bus timeout

gpoa/backend/samba_backend.py
If the kinit fails, an exception is thrown so that execution of gpupdate does not continue
=> Catch exception in case kinit is not successful

gpoa/storage/sqlite_registry.py
This PR is needed for case-insensitive comparison of `hive_key` field in `HKCU` and `HKLM` tables.
=> Make registry keys case-insensitive like in Windows registry

gpoa/frontend/firefox_applier.py
Mozilla Firefox version 78 changed its default `policies.json` file
location to `/etc/firefox/policies/policies.json`. Previous location
does not work despite changelog ensuring it will continue working.
=> Change policies.json location for Firefox

gpoa/frontend/applier_frontend.py, gpoa/frontend/appliers/gsettings.py, gpoa/frontend/gsettings_applier.py, gpoa/messages/__init__.py, gpoa/util/dbus.py, gpoa/util/system.py
- Add new Software\BaseALT\Policies\GPUpdate\WindowsPoliciesMapping feature enables or disables GSettings mapping.
- Fix various debug info mesages during GSetting applying.
- Avoid error in forked process with dconf-service killing if dconf not using.
=> Windows mapping feature and dbus fixes

gpoa/gpt/dynamic_attributes.py
I propose a fix related to the validation of Preference values.
**Problem**: if there were quotes inside a value, parsing from a binary file was impossible (string structure was broken for parsing with python tools: ast.literal_eval, ...).
**Solution**: replace quotation marks with a character similar to a quotation mark
=> Added handling of quotation marks in Preference values
